### ISSUE TITLE
svg event support and jquery

### ISSUE THREAD

**Issue by Neon22** [laffra/ltk#1]
more of a feature request as ltk is looking so good.
- ntoll has a pyscript svg standin here: https://pyscript.com/@ntoll/turtle-workers/latest
- I see a couple of jquery and svg modules kicking around that seem to enable selection/events in svg.

Wondering if you'd like to look into allowing addition of events to svg elements and interaction with the dom etc.
Or give me a few pointers as my jquery foo is weak.

**Comment by laffra** [comment]
Glad you like LTK!

LTK is a very thin layer on top of jQuery. With jQuery you can render any HTML, including SVG. I just added a new example to the LTK Kitchensink that shows how that works. See the [SVG tab](https://laffra.github.io/ltk/?tab=9) and click inside the yellow ellipse.

**Comment by Neon22** [comment]
dude. very cool. congratulations. and getting it to all work in micropython as well. amazing. I have quite a dynamic dom so the @when does not work for me. I will try to convert my half done example and see how it goes.
- https://pyscript.com/@d5127013-0d63-43cd-9926-95380d21cf67/color-harmony-helper/latest

**Comment by Neon22** [comment]
Ahhh. do you have a starter pyscript section/example ?

E.g. Like what I need in pyscript.toml and in index.htm like kitchensink.js and ltk.js.
I am guessing if I do a local install I can copy and paste those files up to pyscript.com ?

**Comment by laffra** [comment]
You do not need to do a local install, you can copy the code from GitHub
directly:

   - https://github.com/laffra/ltk/blob/main/index.html
   - https://github.com/laffra/ltk/blob/main/kitchensink.toml

On MicroPython you cannot import packages from PyPI yet, so you have to
include the LTK source with your application, sadly.
The PyScript team is working on dynamic module loading support, so
MicroPython will look more like PyOdide.

Chris

**Comment by Neon22** [comment]
Thanks heaps Chris, The color harmony helper is a part of my work on pyweaving(unreleased branch) - an online weaving draft editor. This part just to help with color selection. Existing web color model stuff seem very weak. Luckily I worked in feature film effects for many years so I hope I can leverage that and make something useful.

I can wait for micropython so no worries there. hopefully will avoid any special pyiodide stuff because its much faster. But then my other pyweaving code is a bit more intense and so there might be trouble. ah well we will see.

Just trying kitchensink as you describe above. Having minor difficulty with syntax errors. probably did not copy something right. will get back to it later tonight (I'm in NZ and I need to build a deck today). Very much looking fwd to it (even if I have avoided jquery for so long now :))

FYI. The 'new' approach to loading screen appears to be:
in body
```html
<dialog id="loading">
   <h1>Assembling bits and pieces...</h1>
   <h3>Almost there...</h3>
</dialog>
```
and in head under meta tag:
```html
<style>
    #loading { outline: none; border: none; background: transparent }
 </style>
 <script type="module">
    const loading = document.getElementById('loading');
    addEventListener('py:ready', () => loading.close());
    loading.showModal();
</script>
```
of course its not very dynamic but you might find it useful to lower some code overhead ??

I'll have some more questions for you. Shall we just keep going in here ?
I know I need to ask you for your opinion about whichof your three mechanisms for styling is best suited for this project.

**Comment by Neon22** [comment]
I think maybe the fetch in toml is setup for local fs read instead of from pip/pyiodide ?
getting a syntax error on ltk/__init__.py

**Comment by Neon22** [comment]
Alas - not having any luck.
I can't make a subdirectory on pyscript .com to position the ltk within.
also tried a packages = ["ltk"] as well but no luck.

Any ideas?
- https://pyscript.com/@neon22/ltk-attempt/latest

**Comment by laffra** [comment]
I ran into the same issue. I am working on a bundler to put a given besteed
module into one file. That may work.

**Comment by laffra** [comment]
I created two minimal LTK templates on pyscript.com:

   - LTK with MicroPython:
   https://laffra.pyscriptapps.com/ltk-on-micropython/
   - LTK with PyOdide: https://laffra.pyscriptapps.com/ltk-on-pyodide/

Chris

**Comment by Neon22** [comment]
excellent - I have success with both. Thanks
